mysql2:
   image: itaotao/mysql
   ports: 
     - "3306:3306"
   volumes:
     - /var/lib/docker/vfs/dir/dataxc:/var/lib/mysql
   hostname: ItaotaoServer

tomcat:
   image: itaotao/tomcat:7.0.55
   ports:
      - "8080:8080"
   links:
      - mysql2:db
   environment:
      - TOMCAT_USER=admin
      - TOMCAT_PASS=admin
   hostname: ItaotaoServer
